from typing import Any, Dict

from nuplan.common.actor_state.tracked_objects_types import TrackedObjectType
from nuplan.common.maps.abstract_map import SemanticMapLayer
from nuplan.common.maps.maps_datatypes import TrafficLightStatusType

from carl_nuplan.common.colors import (
    BLACK,
    DARK_GREY,
    DARKER_GREY,
    ELLIS_5,
    LIGHT_GREY,
    NEW_TAB_10,
    TAB_10,
    WHITE,
    Color,
)


BEV_PLOT_CONFIG: Dict[str, Any] = {
    "figure_size": (10, 10),
    "figure_xlim": (-64, 64),
    "figure_ylim": (-64, 64),
    "background_color": WHITE,
    "layers": ["map", "tracks"],  # "map", "tracks"
}


MAP_LAYER_CONFIG: Dict[SemanticMapLayer, Any] = {
    SemanticMapLayer.LANE: {
        "fill_color": LIGHT_GREY,
        "fill_color_alpha": 1.0,
        "line_color": LIGHT_GREY,
        "line_color_alpha": 0.0,
        "line_width": 1.0,
        "line_style": "-",
        "zorder": 1,
    },
    SemanticMapLayer.LANE_CONNECTOR: {
        "fill_color": LIGHT_GREY,
        "fill_color_alpha": 1.0,
        "line_color": LIGHT_GREY,
        "line_color_alpha": 0.0,
        "line_width": 1.0,
        "line_style": "-",
        "zorder": 1,
    },
    SemanticMapLayer.WALKWAYS: {
        "fill_color": Color("#d4d19e"),
        "fill_color_alpha": 1.0,
        "line_color": Color("#d4d19e"),
        "line_color_alpha": 0.0,
        "line_width": 1.0,
        "line_style": "-",
        "zorder": 1,
    },
    SemanticMapLayer.CARPARK_AREA: {
        "fill_color": Color("#b9d3b4"),
        "fill_color_alpha": 1.0,
        "line_color": Color("#b9d3b4"),
        "line_color_alpha": 0.0,
        "line_width": 0.0,
        "line_style": "-",
        "zorder": 1,
    },
    SemanticMapLayer.PUDO: {
        "fill_color": Color("#AF75A7"),
        "fill_color_alpha": 0.3,
        "line_color": Color("#AF75A7"),
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "zorder": 1,
    },
    SemanticMapLayer.INTERSECTION: {
        "fill_color": LIGHT_GREY,
        "fill_color_alpha": 1.0,
        "line_color": LIGHT_GREY,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "zorder": 1,
    },
    SemanticMapLayer.STOP_LINE: {
        "fill_color": Color("#FF0101"),
        "fill_color_alpha": 0.0,
        "line_color": Color("#FF0101"),
        "line_color_alpha": 0.0,
        "line_width": 1.0,
        "line_style": "-",
        "zorder": 1,
    },
    SemanticMapLayer.CROSSWALK: {
        "fill_color": NEW_TAB_10[6],
        "fill_color_alpha": 0.3,
        "line_color": NEW_TAB_10[6],
        "line_color_alpha": 0.0,
        "line_width": 1.0,
        "line_style": "-",
        "zorder": 2,
    },
    SemanticMapLayer.ROADBLOCK: {
        "fill_color": DARK_GREY,
        "fill_color_alpha": 1.0,
        "line_color": DARKER_GREY,
        "line_color_alpha": 0.0,
        "line_width": 1.0,
        "line_style": "-",
        "zorder": 1,
    },
    SemanticMapLayer.ROADBLOCK_CONNECTOR: {
        "fill_color": ELLIS_5[1],
        "fill_color_alpha": 0.1,
        "line_color": ELLIS_5[1],
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "zorder": 1,
    },
    SemanticMapLayer.BASELINE_PATHS: {
        "line_color": Color("#666666"),
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "--",
        "zorder": 1,
    },
}

AGENT_CONFIG: Dict[SemanticMapLayer, Any] = {
    TrackedObjectType.VEHICLE: {
        "fill_color": ELLIS_5[4],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": "line",
        "zorder": 3,
    },
    TrackedObjectType.PEDESTRIAN: {
        "fill_color": NEW_TAB_10[6],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": "line",
        "zorder": 2,
    },
    TrackedObjectType.BICYCLE: {
        "fill_color": ELLIS_5[3],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": "line",
        "zorder": 2,
    },
    TrackedObjectType.TRAFFIC_CONE: {
        "fill_color": NEW_TAB_10[5],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": None,
        "zorder": 2,
    },
    TrackedObjectType.BARRIER: {
        "fill_color": NEW_TAB_10[5],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": None,
        "zorder": 2,
    },
    TrackedObjectType.CZONE_SIGN: {
        "fill_color": NEW_TAB_10[5],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": None,
        "zorder": 2,
    },
    TrackedObjectType.GENERIC_OBJECT: {
        "fill_color": NEW_TAB_10[5],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": None,
        "zorder": 2,
    },
    TrackedObjectType.EGO: {
        "fill_color": ELLIS_5[0],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": "line",
        "zorder": 2,
    },
}

TRAFFIC_LIGHT_CONFIG: Dict[TrafficLightStatusType, Any] = {
    TrafficLightStatusType.RED: {
        "line_color": TAB_10[3],
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "--",
        "zorder": 1,
    },
    TrafficLightStatusType.YELLOW: {
        "line_color": TAB_10[1],
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "--",
        "zorder": 1,
    },
    TrafficLightStatusType.GREEN: {
        "line_color": TAB_10[2],
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "--",
        "zorder": 1,
    },
    TrafficLightStatusType.UNKNOWN: {
        "line_color": Color("#666666"),
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "--",
        "zorder": 1,
    },
}

TRAJECTORY_CONFIG: Dict[str, Any] = {
    "human": {
        "fill_color": NEW_TAB_10[4],
        "fill_color_alpha": 1.0,
        "line_color": NEW_TAB_10[4],
        "line_color_alpha": 1.0,
        "line_width": 2.0,
        "line_style": "-",
        "marker": "o",
        "marker_size": 5,
        "marker_edge_color": BLACK,
        "zorder": 3,
    },
    "agent": {
        "fill_color": ELLIS_5[0],
        "fill_color_alpha": 1.0,
        "line_color": ELLIS_5[0],
        "line_color_alpha": 1.0,
        "line_width": 2.0,
        "line_style": "-",
        "marker": "o",
        "marker_size": 5,
        "marker_edge_color": BLACK,
        "zorder": 3,
    },
}
